In [1]:
lista = [5, 9, 10, 3]

In [2]:
import numpy as np

In [3]:
na = np.array(lista)

In [4]:
print(type(na))

<class 'numpy.ndarray'>


In [5]:
print(na)

[ 5  9 10  3]


In [6]:
na[2]

10

In [7]:
listb = [10, 11, 12, 13]
listc = [6, 8, 10, 12]

In [8]:
nb = np.array([lista, listb, listc])

In [9]:
print(nb)

[[ 5  9 10  3]
 [10 11 12 13]
 [ 6  8 10 12]]


In [10]:
na.ndim

1

In [11]:
nb.ndim

2

In [12]:
nb.shape

(3, 4)

In [13]:
np.array([[4, 5], [6, 7]])

array([[4, 5],
       [6, 7]])

In [14]:
nb

array([[ 5,  9, 10,  3],
       [10, 11, 12, 13],
       [ 6,  8, 10, 12]])

In [15]:
print(nb)

[[ 5  9 10  3]
 [10 11 12 13]
 [ 6  8 10 12]]


In [17]:
nc = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [18]:
print(nc)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [20]:
print(nc[1:])

[[40 50 60]
 [70 80 90]]


In [21]:
print(nc[1:, 0:2])

[[40 50]
 [70 80]]


In [22]:
print(nc[1:2, :])

[[40 50 60]]


In [23]:
print(nc[0:1, 1:])

[[20 30]]


In [24]:
print(nb)

[[ 5  9 10  3]
 [10 11 12 13]
 [ 6  8 10 12]]


In [25]:
nd = nb[:, 1:]

print(nd)

[[ 9 10  3]
 [11 12 13]
 [ 8 10 12]]


In [26]:
print(nc)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [27]:
nd + nc

array([[ 19,  30,  33],
       [ 51,  62,  73],
       [ 78,  90, 102]])

In [28]:
nd - nc

array([[ -1, -10, -27],
       [-29, -38, -47],
       [-62, -70, -78]])

In [29]:
nd * nc

array([[  90,  200,   90],
       [ 440,  600,  780],
       [ 560,  800, 1080]])

In [30]:
nd.dot(nc)

array([[ 700,  920, 1140],
       [1500, 1860, 2220],
       [1320, 1620, 1920]])

In [31]:
nd.min()

3

In [32]:
min(nd)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [33]:
nd.mean()

9.777777777777779

In [34]:
nd.std()

2.8196838978776713

In [35]:
nd.var()

7.950617283950617

In [37]:
np.square(nd)

array([[ 81, 100,   9],
       [121, 144, 169],
       [ 64, 100, 144]])

In [39]:
np.power(nd, 3)

array([[ 729, 1000,   27],
       [1331, 1728, 2197],
       [ 512, 1000, 1728]])

In [40]:
np.transpose(nd)

array([[ 9, 11,  8],
       [10, 12, 10],
       [ 3, 13, 12]])

In [41]:
nd.flatten()

array([ 9, 10,  3, 11, 12, 13,  8, 10, 12])

In [43]:
list(nd.flatten())

[9, 10, 3, 11, 12, 13, 8, 10, 12]

In [44]:
nd.size

9

In [45]:
nd.dtype

dtype('int64')

In [50]:
listu = [100, 200, 260, 240]
listv = [222, 134, 167, 120]

ne = np.array([listu, listv], dtype='uint16')

In [51]:
type(ne)

numpy.ndarray

In [52]:
print(ne)

[[100 200 260 240]
 [222 134 167 120]]


In [53]:
listu = [100, 200, 260, 240]
listv = [222, 134, 167, 120]

ne = np.array([listu, listv], dtype='uint8')

In [54]:
print(ne)

[[100 200   4 240]
 [222 134 167 120]]


In [55]:
ne.itemsize

1

In [56]:
nd.itemsize

8

In [57]:
nf = np.arange(7)

In [58]:
print(nf)

[0 1 2 3 4 5 6]


In [59]:
nb.ndim

2

In [60]:
print(nb)

[[ 5  9 10  3]
 [10 11 12 13]
 [ 6  8 10 12]]


In [61]:
nb.shape

(3, 4)

In [62]:
nb.reshape(6, 2)

array([[ 5,  9],
       [10,  3],
       [10, 11],
       [12, 13],
       [ 6,  8],
       [10, 12]])

In [63]:
nb

array([[ 5,  9, 10,  3],
       [10, 11, 12, 13],
       [ 6,  8, 10, 12]])

In [64]:
na

array([ 5,  9, 10,  3])

In [65]:
na[na%2==0]

array([10])

In [66]:
nb[nb%2==0]

array([10, 10, 12,  6,  8, 10, 12])

In [67]:
nb

array([[ 5,  9, 10,  3],
       [10, 11, 12, 13],
       [ 6,  8, 10, 12]])

In [68]:
nb%2==0

array([[False, False,  True, False],
       [ True, False,  True, False],
       [ True,  True,  True,  True]])

In [69]:
nb[nb%2==0].sum()

68

In [70]:
nh = nb.copy()

In [71]:
import time

In [72]:
size = 100000

def funca():
    t1 = time.time()
    x = range(size)
    y = range(size)
    res = [x[i] + y[i] for i in range(len(x))]
    t2 = time.time()
    return t2-t1

def funcb():
    t1 = time.time()
    x = np.arange(size)
    y = np.arange(size)
    res = x+y
    t2 = time.time()
    return t2-t1

numpy_time = funcb()
compr_time = funca()

print("numpy_time =", numpy_time)
print("compr_time =", compr_time)

numpy_time = 0.0005362033843994141
compr_time = 0.030832767486572266


In [75]:
round(compr_time/numpy_time, 3)

57.502

In [76]:
import random

In [77]:
np.random.randint(45)

4

In [78]:
np.random.randint(45)

33

In [79]:
np.random.rand()

0.9867067197616014

In [80]:
np.random.rand()

0.0011766937293260504

In [81]:
np.random.randint(250, size=(6))

array([200, 197,  18, 183, 232,  90])

In [82]:
np.random.randint(250, size=(6, 3))

array([[ 94,  92, 214],
       [153,  77,  67],
       [116, 238, 134],
       [109,  60, 112],
       [213, 230,  55],
       [187,  97,  61]])

In [84]:
np.random.rand(2, 3)*10

array([[9.96115268, 0.60540613, 7.92335875],
       [6.41681939, 3.41240599, 5.01990198]])

In [85]:
listx = [100, 200, 260, 240, 222, 134, 167, 120]

In [86]:
np.random.choice(listx)

100

In [87]:
np.random.choice(listx)

240

In [88]:
np.random.choice(listx, size=(2, 3))

array([[100, 240, 167],
       [100, 200, 100]])

In [91]:
ni = np.zeros((3, 3))

In [92]:
print(ni)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [94]:
np.full((44), shape=(3, 3))

TypeError: full() got multiple values for argument 'shape'

In [95]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    zeros : Return a new array set

In [98]:
np.full((3, 3), 44)

array([[44, 44, 44],
       [44, 44, 44],
       [44, 44, 44]])

In [100]:
np.linspace(4, 5, 8)

array([4.        , 4.14285714, 4.28571429, 4.42857143, 4.57142857,
       4.71428571, 4.85714286, 5.        ])

In [101]:
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [102]:
na

array([ 5,  9, 10,  3])

In [103]:
np.append(na, [5, 6, 7])

array([ 5,  9, 10,  3,  5,  6,  7])

In [104]:
np.random.randint(low=10, high=200, size=10)

array([118, 174, 154, 143, 149, 173, 103,  35,  69, 102])

In [105]:
np.random.randint(low=10, high=200, size=10)

array([107, 172,  32,  71, 180, 154, 164, 128,  20, 161])

In [106]:
np.random.seed(6)
np.random.randint(low=10, high=200, size=10)

array([148, 116, 119,  89, 116,  90,  72,  35,  11,  85])

In [107]:
np.random.seed(6)
np.random.randint(low=10, high=200, size=10)

array([148, 116, 119,  89, 116,  90,  72,  35,  11,  85])

In [108]:
np.random.seed(4)
np.random.randint(low=10, high=200, size=10)

array([132, 184, 193, 139, 114,  97,  60, 147,  68, 113])

In [109]:
np.random.seed(6)
np.random.randint(low=10, high=200, size=10)

array([148, 116, 119,  89, 116,  90,  72,  35,  11,  85])

In [110]:
a = np.array([2,3,4,5,6])

b=a

b=np.append(b,[9,8,7])

a

array([2, 3, 4, 5, 6])

In [111]:
na

array([ 5,  9, 10,  3])

In [112]:
nj = na

In [113]:
nj

array([ 5,  9, 10,  3])

In [114]:
na.sort()

In [115]:
na

array([ 3,  5,  9, 10])

In [116]:
nj

array([ 3,  5,  9, 10])