In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
from sklearn.neighbors import KNeighborsClassifier as KNN

In [4]:
dfa = pd.read_csv('iris.csv')

In [5]:
dfa.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [8]:
dfa.shape

(150, 5)

In [9]:
dfa['class'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [11]:
df_testa = dfa.iloc[7]
df_testb = dfa.iloc[9]
df_testc = dfa.iloc[131]

In [12]:
dfa = dfa.drop([7])
dfa = dfa.drop([9])
dfa = dfa.drop([131])

In [13]:
dfa.shape

(147, 5)

In [14]:
model = KNN(n_neighbors=3)

In [17]:
model.fit(X=dfa[['sepal_length', 'petal_width']], y=dfa['class'])

KNeighborsClassifier(n_neighbors=3)

In [18]:
model.score(X=dfa[['sepal_length', 'petal_width']], y=dfa['class'])

0.9659863945578231

In [19]:
model.predict(df_testa[['sepal_length', 'petal_width']].values.reshape((-1, 2)))

array(['Iris-setosa'], dtype=object)

In [20]:
df_testa['class']

'Iris-setosa'

In [21]:
df_testb['class']

'Iris-setosa'

In [22]:
df_testc['class']

'Iris-virginica'

In [23]:
model.predict(df_testb[['sepal_length', 'petal_width']].values.reshape((-1, 2)))

array(['Iris-setosa'], dtype=object)

In [24]:
model.predict(df_testc[['sepal_length', 'petal_width']].values.reshape((-1, 2)))

array(['Iris-virginica'], dtype=object)

In [25]:
model.predict_proba(df_testc[['sepal_length', 'petal_width']].values.reshape((-1, 2)))

array([[0., 0., 1.]])

In [29]:
dfa = pd.read_csv('iris.csv')

df_testc = dfa.iloc[134]
dfa = dfa.drop([134])

In [36]:
dfa = pd.read_csv('iris.csv')
model = KNN(n_neighbors=13)

model.fit(X=dfa[['sepal_length', 'petal_width']], y=dfa['class'])

model.predict(df_testc[['sepal_length', 'petal_width']].values.reshape((-1, 2)))

array(['Iris-versicolor'], dtype=object)

In [37]:
df_testc['class']

'Iris-virginica'

In [32]:
model.predict_proba(df_testc[['sepal_length', 'petal_width']].values.reshape((-1, 2)))

array([[0.        , 0.66666667, 0.33333333]])

In [38]:
import numpy as np

In [42]:
na = np.array([[5, 7, 8, 10],[3, 6, 1, 8],[5, 7, 8, 2], [5, 7, 8, 4]])

In [43]:
print(na)

[[ 5  7  8 10]
 [ 3  6  1  8]
 [ 5  7  8  2]
 [ 5  7  8  4]]


In [44]:
na.reshape(-1, 8)

array([[ 5,  7,  8, 10,  3,  6,  1,  8],
       [ 5,  7,  8,  2,  5,  7,  8,  4]])

In [45]:
na.reshape(16, -1)

array([[ 5],
       [ 7],
       [ 8],
       [10],
       [ 3],
       [ 6],
       [ 1],
       [ 8],
       [ 5],
       [ 7],
       [ 8],
       [ 2],
       [ 5],
       [ 7],
       [ 8],
       [ 4]])